### ISSUE TITLE
Compatibility with PHP7

### ISSUE THREAD

**Issue by Berdir** [guzzle/RingPHP#22]
Drupal8 has a critical release blocker to be compatible with PHP7.

The installer currently fails because of guzzle. I tried to fix those errors myself, but I can't really make sense of the code, apart from the first one, which seems easy enough to fix:

`Fatal error: Redefinition of parameter $_ in /vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php on line 313`
=> This seems easy enough, I guess it's no longer possible to have multiple identical parametes

`Fatal error: Argument 3 passed to GuzzleHttp\Ring\Client\StreamHandler::createResponse() must be of the type array, null given, called in /vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php on line 34 and defined in /vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php on line 40`
=> I can't figure out where headers would be set, it's just passed around by reference but never set?

`Fatal error: Argument 1 passed to GuzzleHttp\Message\FutureResponse::proxy() must implement interface GuzzleHttp\Ring\Future\FutureInterface, null given, called in /src/RequestFsm.php on line 133 and defined in /src/Message/FutureResponse.php on line 36`
=> This is coming from testCanSpecifyHandler(), somehow that trick with throwing an exception doesn't seem to work anymore...

Didn't get past the last one yet...

**Comment by Berdir** [comment]
For reference, this is the Drupal issue: https://www.drupal.org/node/2454439#comment-9768963

**Comment by Berdir** [comment]
Oh, i actually wanted to open the issue in guzzle, but the errors are in both projects, so it doesn't matter much..

**Comment by Berdir** [comment]
Quick update, fixing the obvious first error with repeated arguments makes the Drupal installer work again, so far it looks like the additional errors are test-specific problems.

**Comment by mtdowling** [comment]
I'll merge any necessary PRs.

**Comment by stefanruijsenaars** [comment]
@Berdir which one of these have you fixed and which do you still need help on? I can have a look but just wondering if you could give any background -- the "trick" is obvious from the code or do I need to know anything?

**Comment by Berdir** [comment]
I've experimented a bit, no real fixes. The $_ fix is easy, only question is how to name the variables, $_1, $_2, $_3 was what I did. A quick OK or a better suggestion from @mtdowling would be useful, before creating a PR.

For the second, I've just added a $headers = array(); before it is used, then it worked for me, but I don't understand what the code is supposed to do. And I don't understand why it works in PHP 5, some by-reference trickery apparently.

No solution for the third yet, would appreciate any guidance on how to proceed there. Looks like we might need a real callback function to test, but I have no idea what that would have to do.

**Comment by mtdowling** [comment]
The first and second errors are fixed.

Haven't looked into the future proxy problem yet.

**Comment by mtdowling** [comment]
Actually, looks like that stream wrapper fix may have inadvertently fixed the future proxy issue: https://travis-ci.org/guzzle/RingPHP/jobs/56357602

Looks like we are good to go on PHP 7 for RingPHP. I'll leave the Guzzle issue open until that's working as well.
