### ISSUE TITLE
Usage of curl_reset which is not available in PHP5.4

### ISSUE THREAD

**Issue by wahler** [guzzle/RingPHP#23]
Class CurlHandler (https://github.com/guzzle/RingPHP/blob/master/src/Client/CurlHandler.php#L114) uses PHP function "curl_reset" which is not available in PHP 5.4

**Comment by mtdowling** [comment]
You can only use that handler if you have PHP 5.5 or greater. It's not required to use the library, it's only conditionally required which means the minimum project version can stay at 5.4.

**Comment by michael-e** [comment]
> it's only conditionally required which means the minimum project version can stay at 5.4

Isn't this against the spirit of Composer? Being able to install an "intentionally broken" package? (I had some trouble with that.)

**Comment by mtdowling** [comment]
No I don't think so. It's not intentionally broken and this feature is documented as requiring PHP 5.5.

**Comment by michael-e** [comment]
Hmmm, you are right, it's in the docs. Thanks!
