### ISSUE TITLE
Add "conflict" with "ext-curl" 7.35 to composer.json

### ISSUE THREAD

**Issue by sascha-egerer** [guzzle/RingPHP#26]
Curl has a regression in version 7.35 which could produce results with "[curl] 56: Problem (2) in the Chunked-Encoded data "

Therefore there should be a "conflict" with "ext-curl" 7.35 in the composer.json.

See also
http://curl.haxx.se/mail/lib-2015-03/0112.html

Regresison is fixed in 7.36 "chunked decoder: track overflows correctly"
http://curl.haxx.se/changes.html#7_36_0

**Comment by sascha-egerer** [comment]
Ah i just saw that it is not possible to set a specific version for curl as "ext-curl" has no version

**Comment by mtdowling** [comment]
Yeah, I don't think we can add that. I bet most users would not get this version of curl as distros would either patch it or use a different version. Maybe this issue will help people who are bit by this when they google it.
