### ISSUE TITLE
GAE Support

### ISSUE THREAD

**Issue by lifeofguenter** [guzzle/RingPHP#37]
Would be great to get it supported under Google App Engine (PHP):
- https://github.com/guzzle/RingPHP/blob/9465032ac5d6beaa55f10923403e6e1c36018d9c/src/Client/StreamHandler.php#L279 - this doesn't work, it does not accept `cafile` as an option
- https://github.com/guzzle/RingPHP/blob/9465032ac5d6beaa55f10923403e6e1c36018d9c/src/Client/StreamHandler.php#L295 - this option is unsupported

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but I'm going to close this since this repo has been EOL for a while now.
