### ISSUE TITLE
Would it block if the request URL is pretty slow ?

### ISSUE THREAD

**Issue by haikuoyao** [guzzle/RingPHP#38]
Hi,

I'm looking for a `fire and forget` request to use in my code.
This is my test code. 

```
if (!empty($_GET['ring']))
{
    notice('Ring request hit');
    sleep(10);
    die('The End.');
}

$handler = new GuzzleHttp\Ring\Client\CurlMultiHandler();

$request = [
    'http_method' => 'GET',
    'scheme'      => 'http',
    'uri'         => '/test.php?ring=1',
    'headers'     => [
        'host' => ['test'],
    ],
    'future'      => 'lazy'
];
$response = $handler($request);
```

I don't want my code is blocked by request.
But it's still blocked 10s by request when I set `future`.

Can I use `RingPhp` to do this ?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but I'm going to close this since this repo has been EOL for a while now.
