### ISSUE TITLE
Bump minimum react promise version to 2.2 at least

### ISSUE THREAD

**Issue by jayS-de** [guzzle/RingPHP#39]
I was running into some issues when trying to install guzzle with lowest possible version on a PHP 7.1 environment.

For PHP 7.1 the minimum version of Guzzle has to be 5.3.1. When installing 5.3.1 --prefer-lowest flag composer installs react/promise in version 2.0.0. But as in 2.2.0 the Deferred::progress has been renamed to Deferred::notify.

The solution is now for me to add a development dependency to at least react/promise 2.2.0. This should also be done either in the guzzle 5.3 branch or in the ring php library

**Comment by jayS-de** [comment]
See also this commit: https://github.com/guzzle/guzzle/commit/955957d

**Comment by Nyholm** [comment]
Thank you @jayS-de for reporting this. 

To address this issue I've made sure we test with the prefer lowest flag on RingPHP. I also submitted a patch to guzzle/guzzle that will fix this issue.

**Comment by sagikazarmark** [comment]
Since the related PRs are merged, this can be closed I guess.

**Comment by Nyholm** [comment]
Yes, thank you.
