### ISSUE TITLE
fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by atefBB** [guzzle/RingPHP#43]
I'm using guzzle ringPHP with laravel 4.2 on win7, and when I try to get a webpage I got the error:
`fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known ~/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php [line] 406`.
the line 406 in `~/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php` is : 
`$resource = fopen($url, 'r', null, $context);`

any ideas?

**Comment by victorngure** [comment]
Hello,
Did you manage to solve this error?

**Comment by atefBB** [comment]
Hi @victorngure !
Sorry for the late response. 
I quit the project that I face this issue in so I forgot it!
Sorry one more time.

**Comment by victorngure** [comment]
Ok @atefBB 
Thanks for the response

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but I'm going to close this since this repo has been EOL for a while now.
