### ISSUE TITLE
Drop React/Promise dependency

### ISSUE THREAD

**Issue by apokryfos** [guzzle/RingPHP#49]
GuzzleHttp seems to now have its own promise interface in guzzle/promises which seems to be implementing the same standard. It probably makes more sense to use this one since it is so much more likely for people to be using that (starred 4k+ times) over the react/promises one (starred 1.6k+ times) therefore it will reduce the likelihood of people getting 2 different promise implementations and all the potential "my IDE auto-included the wrong interface and now I'm getting type errors" situation .

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but I'm going to close this since this repo has been EOL for a while now.
